spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

kakao:
  rest-api-key: 0c9e80288d005feed95d073439ac743e

logging:
  level:
    com.heedoitdox.searchblogservice.external: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE